validations:
  - name: Hubspot GCP - budget
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/budget.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_budget
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - exchangeRate
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/exchangeRate.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_exchangeRate
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_2024
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_2024.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_2024
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_2024_treated
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_2024_treated.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_2024_treated
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_2025
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_2025.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_2025
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_2025_treated
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_2025_treated.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_2025_treated
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_2026
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_2026.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_2026
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_2026_treated
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_2026_treated.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_2026_treated
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_all_years
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_all_years.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_all_years
    primary_keys: []
    output_dir: ./results/hubspot_gcp

  - name: Hubspot GCP - mrr_monthly_by_group
    source:
      type: file
      path: "./raw_data/Hubspot GCP files/mrr_monthly_by_group.csv"
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: hubspot_gcp_mrr_monthly_by_group
    primary_keys: []
    output_dir: ./results/hubspot_gcp


# python3 main.py --config config/1hubspotGCPfiles.yaml