
validations:
  - name: "SF Profile Validation"
    source:
      type: file
      path: ./data/SF_profile.csv
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: salesforce_profile
    primary_keys: id
    output_dir: ./results/sf_profile_validation