validations:
  - name: "VartopiaDRS__Registration Validation"
    source:
      type: file
      path: ./raw_data/VartopiaDRS__Registration__c.csv
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: salesforce_vartopiadrs__registration__c
      where_clause: "edw_act_fl = 'Y'"
    primary_keys: id
    output_dir: ./results/salesforce_vartopiadrs__registration
  