validations:
  - name: "salesforce_entitydefinition Validation"
    source:
      type: file
      path: ./raw_data/EntityDefinition.csv
    target:
      type: table
      environment: PREPROD
      schema: edw_asis
      table: salesforce_entitydefinition
      where_clause: "edw_act_fl = 'Y'"
    primary_keys: id,qualifiedapiname
    output_dir: ./results/salesforce_entitydefinition



# --------- SFDC QUERIES FOR REFERENCE ---------
# select defaultimplementation, extendedby, extendsinterfaces, implementedby, implementsinterfaces, isinterface, isautoactivitycaptureenabled, issubtype, hassubtypes, externalsharingmodel, internalsharingmodel, recordtypessupported, islayoutable, publisherid, runninguserentityaccessid, helpsettingpageurl, helpsettingpagename, editdefinitionurl, newurl, editurl, detailurl, ismruenabled, isqueryable, isfeedenabled, iseverdeletable, iseverupdatable, isevercreatable, isidenabled, istriggerable, issearchable, issearchlayoutable, isretrieveable, isreplicateable, iscustomsetting, keyprefix, deploymentstatus, iscompactlayoutable, isprocessenabled, isworkflowenabled, isapextriggerable, iscustomizable, defaultcompactlayoutid, plurallabel, label, masterlabel, developername, namespaceprefix, qualifiedapiname, lastmodifiedbyid, durableid, id, lastmodifieddate from EntityDefinition limit 2000

# --------- REDSHIFT QUERIES FOR REFERENCE ---------
# select count(*) 
# from edw_asis.salesforce_entitydefinition
# where edw_act_fl = 'Y'

# select column_name from information_schema.columns
# where table_schema = 'edw_stage'
# and table_name ilike '%stg_salesforce_entitydefinition%'
# order by table_name